name: Deploy Website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan cliveholloway.net >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -az --delete ./ clive@cliveholloway.net:~/herbert/

      - name: Set up venv and run post-deploy script
        run: |
          ssh -i ~/.ssh/id_ed25519 clive@cliveholloway.net << 'EOF'
            set -e
            cd ~/herbert
            [ -d .venv ] || python3 -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python ./journal_processing/scripts/extract.py
          EOF

