name: Deploy Journal code

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LibreOffice and process files
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice --no-install-recommends
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e .
          herbert extract data/HerbertHollowayJournals.docx

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan cliveholloway.net >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -az --delete -e "ssh -i ~/.ssh/id_ed25519 -o ServerAliveInterval=30" ./ clive@cliveholloway.net:~/herbert/

      - name: Server cleanup
        run: |
          ssh -i ~/.ssh/id_ed25519 -o ServerAliveInterval=30 -o ConnectTimeout=60 clive@cliveholloway.net "cd ~/herbert && echo 'Deploy complete at $(date)'"
